### ISSUE TITLE
[Sugestão] Remoção da instalação para utilização em aula

### ISSUE THREAD

**Issue by Pliavi** [caio000/codeigniter-basic#1]
Esse repo será usado para o treinamento do pessoal do ClassClock?
A instalação (de onde baixar ou usar composer) mantida para uma consulta posterior fora o treinamento é uma boa, porém nele nem tanto.
Ensinar instalação pode ser perda de tempo útil da aula, até porque ninguém fará instalação durante o trabalho encima do ClassClock.
Acho que poderia ser melhor explicar como cloná-lo do git para a pasta do server.

**Comment by caio000** [comment]
A ideia é criar um material de consulta para todos, não apenas para o treinamento.
O caso da instalação é  apenas para quem ficar interessado em desenvolver algum projeto futuro.
